/**
 * Make node within the supplied prototype execution context.
 * @param {object} context Isolated model state and explicitly wired operations.
 * @param {*} kind kind input accepted by the regression model.
 * @param {*} name name input accepted by the regression model.
 * @returns {*} The modeled operation result; mutating operations update this context.
 */
export function makeNode(context, kind, name) {
  return {
    kind,
    name,
    parent: null,
    root: null,
    pos: 0,
    children: null,
    index: null,
    itemFactory: null,
    omitTrailing: false,
    fragments: null,
    conditionalKids: null,
    fragOn: null,
    nextFragOn: null,
    fragStamp: -1,
    conditional: false,
    declaredBy: null,
    defaultValue: undefined,
    schema: null,
    effectiveSchema: null,
    shapePresent: false,
    controls: {
      active: true,
      visible: true,
      readOnly: false,
      disabled: false
    },
    controlNext: null,
    controlLayers: [],
    expressionDefault: undefined,
    clearExpression: undefined,
    clearWas: false,
    clearNext: false,
    unconditional: false,
    raw: undefined,
    pendingRaw: undefined,
    hasPending: false,
    reported: context.NOREPORT,
    extras: null,
    pendingExtras: null,
    hasPendingExtras: false,
    local: context.MISSING,
    emit: context.MISSING,
    localKeys: context.EMPTY_KEYS,
    nextLocal: context.MISSING,
    nextEmit: context.MISSING,
    nextLocalKeys: context.EMPTY_KEYS,
    stamp: -1,
    settle: null,
    nextSettle: null,
    active: true,
    actNext: true,
    dirty: false,
    dirtyKids: null,
    replaced: false,
    absent: true,
    detached: false,
    listeners: null,
    revision: 0,
    signals: 0,
    callerLoaded: false,
    loaded: false,
    isSource: false,
    srcWritten: false,
    edgeRef: context.MISSING,
    edgeRefEntry: -1,
    entryFragOn: null,
    entryFragEntry: -1,
    hintOrder: null,
    injections: null,
    options: null,
    onChange: null,
    onValidate: null,
    initialValue: undefined,
    replacedHosts: null,
    computedHosts: null,
    dispatching: false,
    waveQueue: null,
    entryDepth: 0,
    entryEmit: context.MISSING,
    entryCommit: 0,
    entrySettles: 0,
    entryWaves: 0,
    commitNumber: 0,
    onChangeDepth: 0,
    entryId: 0,
    autoLog: null,
    loadedList: null
  };
}
