import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  canard: [
    {
      type: 'category',
      label: '@canard',
      items: [{ type: 'autogenerated', dirName: 'canard' }],
    },
  ],
  lerx: [
    {
      type: 'category',
      label: '@lerx',
      items: [{ type: 'autogenerated', dirName: 'lerx' }],
    },
  ],
  winglet: [
    {
      type: 'category',
      label: '@winglet',
      items: [{ type: 'autogenerated', dirName: 'winglet' }],
    },
  ],
};

export default sidebars;
