import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  canard: [
    {
      type: 'autogenerated',
      dirName: 'canard',
    },
  ],
  lerx: [
    {
      type: 'autogenerated',
      dirName: 'lerx',
    },
  ],
  winglet: [
    {
      type: 'autogenerated',
      dirName: 'winglet',
    },
  ],
  slats: [
    {
      type: 'autogenerated',
      dirName: 'slats',
    },
  ],
};

export default sidebars;
