// Measurement-only artifact renderer; host writes are performed by the native file tool.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
const work=path.dirname(fileURLToPath(import.meta.url)),D=path.dirname(work),repo=path.resolve(D,'../../../../../..');
const HEAD='3b38c7092272dc281c8997b76ea7d2e4dae91e57';
const read=(f,folder=work)=>JSON.parse(fs.readFileSync(path.join(folder,f+'.json'),'utf8'));
const hash=v=>createHash('sha256').update(v).digest('hex');
const q=(v,p)=>v.toSorted((a,b)=>a-b)[Math.ceil(v.length*p)-1],median=v=>q(v,.5);
const us=n=>(n*1000).toFixed(3),pct=n=>n.toFixed(2);
const files=fs.readdirSync(work),official=read('official-summary'),history=read('historical-endpoints'),bounds=read('bounds-final-summary');
const fixtures=['flat-100','flat-500','nested-d5-f4','sample-0'];
const specs=[
  {id:'D1',variant:'delivery-scan',label:'커밋 배달 후보·방문 전체',owner:'core/settle',file:'utils/commit/markCommitDeliveries.ts',fix:'globalState.nodes와 candidates를 합칠 때 두 번째 ordered Set을 만들지 않고 기존 globalState.nodes의 membership을 재사용해 같은 순서로 한 번씩 방문합니다. global-state 후보 다음의 추가 후보 순서와 전체 revision 증가 완료 뒤 배달하는 순서를 유지합니다.',contracts:['EVENT-007'],why:'후보 합치기와 방문 순서가 배달 집합 전체의 revision 증가를 빠뜨리거나 리스너보다 뒤로 미루지 않는지 원장 질문이 필요합니다.',elision:'markCommitDeliveries 전체를 생략합니다. global-state 방문·후보/required 처리·배달 비교·payload·revision까지 포함하므로 E1과 크게 겹칩니다.'},
  {id:'E1',variant:'event-mark',label:'사건 표시와 그 후속 비용',owner:'core/record',file:'utils/markSchemaNodeEvent.ts',fix:'UpdateValue의 흔한 표시 경로를 단형 객체 리터럴/대입 경로로 특화하여 pendingDelivery와 payload/options 사전의 일시적 모양 변화를 줄입니다. 기존 runtime 집합과 pendingRevision 비트는 모두 유지하고 외부에 전달한 payload를 재사용하지 않습니다.',contracts:['EVENT-007'],why:'이 함수의 pendingRevision와 revisionNodes가 커밋의 일괄 증가 입력이므로 표시를 싸게 하면서도 리스너 유무와 관계없는 집합과 일괄 증가를 보존해야 합니다.',elision:'markSchemaNodeEvent를 생략합니다. 해당 표시에서 발생하는 revision-ledger 생성 및 dispatch의 후속 처리 감소도 포함합니다. 순수 marker self만의 상한이 아닙니다.'},
  {id:'C1',variant:'commit-bookkeeping',label:'커밋 진단·메모 정리',owner:'core/settle',file:'utils/commit/commitSettlement.ts',fix:'불일치 경로가 계속 비어 있는 경우의 typeMismatchesMemo 갱신을 기존 빈 경로 row의 commit 갱신으로 특화합니다. 비어 있지 않은 상태에서 비는 전이는 기존 초기화를 유지하고 현재 commit 검사와 경고·진단 방문은 보존합니다.',contracts:[],why:'EVENT-007의 증가 루프와 VALUE-012의 조립은 기존 함수를 그대로 소비합니다. 진단/메모 의미를 건너뛰는 수정안은 아닙니다.',elision:'commitNumber 증가와 markCommitDeliveries만 남깁니다. 진단 방문·타입 불일치 메모·refresh/비활성 값 메모 등을 함께 제거한 포괄 상한입니다.'},
  {id:'F1',variant:'fixed-shell',label:'쓰기당 고정 진입·빈 단계 검사',owner:'core/settle',file:'utils/write/writeSchemaNode.ts; utils/settlement/finishSettlement.ts',fix:'기존 branchless·파생 없음·정상 live scalar 조건에 한정하여 고정 진입과 빈 단계 검사를 같은 owner의 단형 호출 경로로 특화합니다. 표시·계산·파생·전이·커밋·배달의 의미와 순서는 유지하고 일반 조건은 기존 경로를 사용합니다.',contracts:[],why:'revision 증가나 assembly 구현을 고치지 않습니다. SETTLE-001의 단계·순서를 생략하는 설계 변경은 이 수정안의 범위 밖입니다.',elision:'writeSchemaNode의 일반/latent/wrong-kind 진입 검사와 finishSettlement의 이 픽스처에서 비어 있는 후처리 검사를 생략합니다. 모든 고정 비용을 제거한 실험은 아니며 C1/P1과 겹칩니다.'},
  {id:'O1',variant:'output-replay',label:'전체 출력 조립·투영·참조 결정',owner:'core/settle',file:'utils/compute/updateOutput.ts',fix:'settlement 한 호출 안에서 사용하는 assembly hint 객체를 owner 내부 WeakMap으로 재사용하고, 매 assemble 직전에 incremental을 false로 초기화합니다. 가상 노드 재진입에서도 이전 hint의 상태를 읽지 않도록 합니다.',contracts:['VALUE-012'],why:'hint.incremental은 얕은 참조 비교/복원의 경로를 결정합니다. hint 수명과 재진입이 바뀌어도 입력 네 종류의 변화와 이전 참조 복원을 보존하는지 원장 질문이 필요합니다.',elision:'미리 기록한 local/emit/changed를 재생하고 change capture를 유지합니다. 조립·투영·참조 결정을 함께 제거하므로 A1을 포함합니다.'},
  {id:'S1',variant:'scratch-release',label:'정착 scratch 정리',owner:'core/settle',file:'utils/write/releaseSettlementScratch.ts',fix:'고정 scratch 컨테이너마다 실제 비어 있지 않을 때만 clear/길이 초기화를 호출하는 단형 경로로 바꿉니다. inUse 해제와 모든 사용한 컨테이너의 초기화는 항상 유지합니다.',contracts:[],why:'배달/조립은 끝난 뒤의 내부 정리이며 revision과 emit 구현은 그대로입니다.',elision:'정리 호출을 clock 밖으로 이동합니다. 실제 작업 제거가 아니라 정리 비용의 제거 실험입니다.'},
  {id:'A1',variant:'assembly-replay',label:'객체 조립',owner:'core/behaviors/objectBehavior',file:'branch/utils/assembleObject.ts',fix:'STABLE_SHAPES가 증명한 같은 children/schema/extras와 키 집합에 한하여 첫 patch의 객체 spread를 고전 루프 복사로 비교합니다. 현재 own 키 순서와 writeObjectKey의 특수 키 처리를 유지하고 메타데이터가 맞지 않으면 기존 경로를 사용합니다.',contracts:['VALUE-012'],why:'새 컨테이너를 만드는 조건, 키 순서, 자식 emit 참조 및 같은 값의 이전 참조 복원을 직접 건드립니다. 원장 질문 뒤에만 제품 수정으로 진행할 수 있습니다.',elision:'assembleObject 결과를 재생합니다. 조립 lookup/copy를 제거하지만 재생 lookup과 hint 설정 비용이 남습니다.'},
  {id:'R1',variant:'recalculation',label:'재계산 등록·조상 경로 확장',owner:'core/settle',file:'utils/write/registerRecalculation.ts',fix:'의존 확장 후 dirty path가 하나이고 게이트가 없는 경우 expanded Set을 만들지 않고 그 경로의 조상만 직접 등록합니다. 여러 경로나 게이트 조건은 기존 경로를 사용합니다.',contracts:[],why:'의존 확장과 dirtyChildren의 입력은 유지하고 revision/assembly 구현은 수정하지 않습니다.',elision:'이 픽스처의 단일 leaf 조상 경로를 직접 등록하여 dependency 질의와 중복 검사 작업을 생략합니다.'},
  {id:'Q1',variant:'compute-shell',label:'계산 경로의 검사·방문 shell',owner:'core/settle',file:'utils/compute/computeNode.ts',fix:'branchless이며 shape가 변하지 않은 계산 몸통을 같은 함수의 단형 호출 자리로 특화합니다. 더티 확인, stateDirty 표시, child post-order, updateOutput 호출과 더티 삭제는 유지합니다.',contracts:[],why:'종류별 assemble와 reference 복원은 기존 updateOutput을 그대로 소비합니다. 단계 순서나 호스트 바퀴는 바꾸지 않습니다.',elision:'정상 leaf/branch 계산의 일반 shape/gate 검사를 생략하고 기존 dirtyChildren/updateOutput을 호출합니다.'},
  {id:'P1',variant:'fixed-empty-latent',label:'빈 latent 저장소의 고정 작업',owner:'core/settle',file:'utils/write/pruneLatentRaw.ts',fix:'runtime.latentRaw.size가 0일 때 childPaths와 call-local latent index를 만들기 전에 반환합니다. 비어 있지 않은 저장소의 prefix 제거·rollback 처리는 유지합니다.',contracts:[],why:'빈 저장소의 작업만 제거하며 revision과 emit 조립은 고치지 않습니다.',elision:'측정 root의 latentRaw가 비어 있음을 단언한 뒤 pruneLatentRaw를 생략합니다.'},
  {id:'W1',variant:'scalar-mark',label:'scalar 표시의 일반 분기',owner:'core/settle',file:'utils/write/markWrite.ts',fix:'기존 정상 terminal·명시적 scalar 쓰기를 단형 분기로 특화하여 branch/virtual/load/automatic 검사만 줄입니다. interpret와 SameValueZero, writtenInputs 및 모든 dirty/changed 표시는 유지합니다.',contracts:[],why:'raw 표시의 분기 특화이며 assembly나 커밋 revision 증가를 고치지 않습니다.',elision:'이 픽스처의 terminal 입력 몸통만 직접 실행합니다.'},
];
const contracts={
  'EVENT-007':{source:'architecture/ledger/event.md:172',sentence:'**원장** — `revision`은 **커밋 시 배달 집합 전체를 한 번에** 올린다',supplement:'65C-03은 변경을 알아내는 구현은 바꿀 수 있으나 구독한 노드에만 payload/revision을 만드는 S4는 하지 않는다고 정합니다.'},
  'VALUE-012':{source:'architecture/ledger/value.md:215',sentence:'**9. `emit`의 참조**는 (자식 `emit` 참조 ∪ `extras` ∪ 호스트 `raw` ∪ 활성 키 집합) 가운데 하나라도 바뀌면 새로 만들고, 아니면 이전 참조를 그대로 둔다(F9).',supplement:'새로 만든 것이 직전 커밋의 것과 키 목록(순서 포함)도 같고 키마다의 자식 `emit` 참조도 같으면 직전 참조를 둔다(얕은 비교, 재계산 목록의 호스트만).'},
};
function aggregateCpu(fixture,mode){const records=[1,2,3].map(r=>read(`cpu-execution-${fixture}-${mode}-r${r}`));const denominatorUs=records.reduce((s,r)=>s+r.cpu.denominatorUs,0),map=new Map();for(const r of records)for(const f of r.cpu.functions){const key=f.function+'|'+f.file+(f.function==='(anonymous)'?':'+f.line:'');const row=map.get(key)??{function:f.function,file:f.file,line:f.line,selfUs:0,totalUs:0};row.line=Math.min(row.line,f.line);row.selfUs+=f.selfUs;row.totalUs+=f.totalUs;map.set(key,row);}const functions=[...map.values()].map(r=>({...r,selfPct:r.selfUs/denominatorUs*100,totalPct:r.totalUs/denominatorUs*100})).sort((a,b)=>b.selfUs-a.selfUs);return {fixture,mode,runs:3,warmup:20,updatesPerRun:101,requestedIntervalUs:10,engineInstrumentation:false,forcedGc:false,preparedRoots:101,window:'동기 write/find/setValue 호출의 실행 구간; endpointCpu는 64 checkpoints와 sentinel까지 별도 보존',denominatorUs,windowUs:records.reduce((s,r)=>s+r.cpu.windowUs,0),sampleIntervals:records.reduce((s,r)=>s+r.cpu.samples,0),selfConservationUs:functions.reduce((s,r)=>s+r.selfUs,0),functions,top20:functions.slice(0,20),sourceFiles:records.map(r=>`cpu-execution-${fixture}-${mode}-r${r.run}.json`)};}
const cpu=fixtures.flatMap(f=>['first','later'].map(m=>aggregateCpu(f,m)));
function coverage(f){const file=f.file,name=f.function;if(file==='(V8)'||file.startsWith('node:')||file.includes('profile-109-update/measure.mjs')||file==='(in-memory loader)')return {ids:[],disposition:'VM/측정 드라이버: 분모에 유지. 제품 owner가 없어 독립 수정안 없음. GC 할당 몫은 A1/O1/E1/S1에 겹치며 강제 GC 위치를 바꿔 독립 판정 상한으로 만들지 않음.'};if(/markSchemaNodeEvent|SchemaNodeRevisionLedger/.test(file+name))return {ids:['E1','D1'],disposition:'사건 표시와 일괄 revision의 중첩 상한'};if(/markCommitDeliveries|commitGlobalState/.test(file))return {ids:['D1','E1'],disposition:'배달 방문 전체와 사건 표시 부분 상한'};if(/commitSettlement/.test(file))return {ids:['C1','D1'],disposition:'자체 정리와 배달 자손을 분리함'};if(/updateOutput|captureSchemaNodeChange|sameValue|projectObject|projectArray/.test(file))return {ids:['O1','A1'],disposition:'전체 출력과 객체 조립 부분 상한'};if(/assembleObject|writeObjectKey/.test(file))return {ids:['A1','O1'],disposition:'조립과 전체 출력의 중첩 상한'};if(/computeNode|dirtyChildren/.test(file))return {ids:['Q1','O1','R1'],disposition:'계산 shell과 출력/경로 자손 상한'};if(/registerRecalculation|DirtyPathSet|getDependencyIndex/.test(file))return {ids:['R1'],disposition:'경로 등록 상한'};if(/markWrite|interpret/.test(file))return {ids:['W1'],disposition:'표시/해석 상한'};if(/releaseSettlementScratch/.test(file))return {ids:['S1'],disposition:'정리 상한'};if(/writeSchemaNode|getSettlementScratch|createSettlementContext|finishSettlement|getLatentPathIndex|pruneLatentRaw/.test(file))return {ids:['F1','P1','W1','R1','Q1','O1','C1','D1'],disposition:'고정 shell과 자손 범위. inclusive total을 별도 이득으로 중복 계산하지 않음'};if(/core\/dispatch|core\/SchemaNode/.test(file))return {ids:['F1','D1','E1','C1','O1'],disposition:'위임/배달의 inclusive 별칭. pooled 자체 self는 5% 미만이므로 자손 상한에 귀속하고 새 독립 제거 상한을 중복하지 않음'};return {ids:[],disposition:'미귀속'};}
const thresholdCoverage=cpu.flatMap(c=>c.functions.filter(f=>f.totalPct>=5).map(f=>({fixture:c.fixture,mode:c.mode,...f,...coverage(f)})));
assert(!thresholdCoverage.some(r=>r.disposition==='미귀속'));
function decompose(round,fixture){const folder=round===109?work:path.join(D,round===107?'profile-107-remaining':'profile-108-ratios'),cal=round===109?official.calibration:round===107?read('profile-107-remaining-summary',D).calibration:read('calibration',folder).byValidation.off,raw=[1,2,3].flatMap(run=>read(`official-${fixture}${round===107?'':'-off'}-r${run}-new`,folder).timings['update-first']),micro=median(raw.map(x=>x[0])),end=median(raw.map(x=>x[1])),tail=median(raw.map(x=>x[1]-x[0]));return {round,fixture,microMs:micro,endMs:end,tailMedianMs:tail,waitMs:cal.C-cal.M,tailResidualMs:tail-(cal.C-cal.M),nonAdditiveMs:end-micro-tail,differenceMs:end-micro-(cal.C-cal.M)};}
const decomposition=[107,108,109].flatMap(r=>['flat-100','array-100'].map(f=>decompose(r,f)));
const diagnostics=files.filter(f=>/^diagnostic-.*\.json$/.test(f)).map(f=>{const r=read(f.slice(0,-5));return {file:f,fixture:r.fixture,run:r.run,placement:r.emptyPlacement,emptyTailMedianMs:median(r.raw.empty.map(x=>x[1]-x[0])),shadowTailMedianMs:r.raw.shadow.length?median(r.raw.shadow.map(x=>x[1]-x[0])):null,firstPartsMedianMs:[0,1,2].map(i=>median(r.raw.first.map(x=>x.parts[i]))),tailCpuTop:r.cpuByPart?.tail.functions.slice(0,10)};});
const ranking=specs.map(s=>{const rows=bounds.rows.filter(r=>r.variant===s.variant&&r.aboveNoise).sort((a,b)=>b.pairedMedianMs-a.pairedMedianMs);return {...s,best:rows[0]??null,positiveRows:rows.length,materialRegressions:bounds.rows.filter(r=>r.variant===s.variant&&r.materialRegression)};}).sort((a,b)=>(b.best?.pairedMedianMs??0)-(a.best?.pairedMedianMs??0));
const rawFiles=files.filter(f=>/^bound-.*\.json$|^official-.*-r[123]-(new|old)\.json$|^cpu-.*\.json$|^diagnostic-.*\.json$/.test(f));
const records=rawFiles.map(f=>({file:f,...read(f.slice(0,-5))}));
for(const r of records){const receipt=r.workerExit??r.summary.workerExit;assert.equal(receipt.code,0);assert.equal(receipt.signal,null);assert.equal(receipt.natural,true);const ms=r.elapsedMs??r.summary.workerExit.elapsedMs;assert(ms<480000);if(r.profileEvidence){const data=gunzipSync(Buffer.from(r.profileEvidence.data,'base64'));assert.equal(hash(data),r.profileEvidence.sha256);JSON.parse(data);}if(r.kind==='bound'){for(const v of ['head','variant'])for(const mode of ['first','later'])assert.equal(r.timings[v][mode].length,101);assert.deepEqual(r.digests.head,r.digests.variant);}if(r.summary){assert.equal(r.summary.environment.head,HEAD);assert.equal(r.summary.officialEngineInstrumentation,false);assert.equal(r.summary.sampleCount,101);for(const order of Object.values(r.summary.ordering)){assert.equal(order.pendingAtSentinel.p99,0);assert.equal(order.tailScheduled.p99+order.tailExecuted.p99,0);if(r.summary.version==='new')assert.equal(order.scheduled.p99,0);}}}
const timeline=records.map(r=>({file:r.file,started:r.started??r.summary.environment.started,ended:r.ended??r.summary.environment.ended})).sort((a,b)=>a.started.localeCompare(b.started));for(let i=1;i<timeline.length;i++)assert(Date.parse(timeline[i].started)>Date.parse(timeline[i-1].ended));
assert.equal(execFileSync('git',['--no-optional-locks','rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),HEAD);
assert.equal(execFileSync('git',['--no-optional-locks','diff','--name-only','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),'');
const artifactManifest=files.map(f=>({file:f,bytes:fs.statSync(path.join(work,f)).size,sha256:hash(fs.readFileSync(path.join(work,f)))}));assert(artifactManifest.every(f=>f.bytes<=5000000));assert(!files.some(f=>/\.(cjs|map|cpuprofile)$|cache/i.test(f)));
const audit={head:HEAD,trackedDiff:false,gitWrites:false,installs:false,bundleMapCacheInRepository:false,bundleLocation:'/private/tmp/claude-501/-Users-Vincent-Workspace-albatrion/c8aaf054-1ea7-43d3-b3c1-a4196f8407e1/scratchpad/bundles',compileCacheDisabled:true,sequential:true,measurementOverlap:false,successfulWorkers:records.length,officialWorkers:records.filter(r=>r.summary).length,boundWorkers:records.filter(r=>r.kind==='bound').length,cpuWorkers:records.filter(r=>r.kind==='cpu').length,diagnosticWorkers:records.filter(r=>r.kind==='endpoint-diagnostic').length,maxWorkerElapsedMs:Math.max(...records.map(r=>r.elapsedMs??r.summary.workerExit.elapsedMs)),extensionBatchElapsedMs:[427840,322948,201889,102639],maximumArtifactBytes:Math.max(...artifactManifest.map(f=>f.bytes)),artifactManifest,started:timeline[0].started,ended:timeline.at(-1).ended,preflightIssues:['기본 yarn node가 Node 24로 실행되어 버전 단언에서 exit 1; 이후 기존 Node 26.10.0 실행 파일을 명시함','진단 프로파일 출력 준비 중 두 번 stdout 전송 한도 초과; 공식 표본 계열에 속하지 않으며 판정에 사용하지 않음. gzip 원문과 해시로 수정하여 유효 진단 원문 보존','sample-0 필터 어댑터 누락과 두 번째 esbuild 서비스 사용 준비가 각각 exit 1; 표본 루프 전에 종료. 필터 및 두 번 빌드 후 stdin EOF 종료를 수정함']};
const packet={title:'109 갱신 경로 귀속과 제거 실험 상한',HEAD,environment:{node:'v26.10.0',v8:'14.6.202.34-node.35',cpu:'Apple M1 Max'},editorDecisions:['106C-01 (416613c70)','105C-01 및 2026-10-07 최소 크기 부록','95C-01','104라운드 소유자 범위'],part1:{cause:'새 엔진의 추가 작업이 아니라, 같은 호출의 microtask 뒤 sentinel 대기를 빈 호출의 상수로 빼고 두 끝점의 주변 중앙값을 따로 합성하는 보정/집계 문제입니다. flat-100의 108 신규 실패는 대기 중앙값 증가가 아니라 비가산 항 증가에 귀속됩니다.',endpoint:'calibrated end-to-end, microtask 이후 sentinel tail',stageAttribution:{write:'양 끝점이 공유하는 동기 구간',settle:'양 끝점이 공유하는 동기 구간',delivery:'새 엔진 예약/추가 실행 0; 정착·배달 실행은 microtask 경계 전',reactCommit:'코어 worker는 React renderer를 호출하지 않음'},sharedArrayCause:true,sharedArrayQualification:'보정/집계의 근본 원인은 같습니다. 107 array의 초과는 비가산 항이, 108 array의 초과는 대기 잔차가 주도합니다. array-100은 interactionCount=1이라 BF와 first가 같은 표본입니다.',decomposition,official,diagnostics,officialDesignChanged:false,samplesDropped:0,newEngineOldFallbackUsed:false},cpu,bounds:{method:'production, fresh process, warmup 20, 101쌍, 표본별 순서 교대, schema clone/강제 GC/anchor가 clock 밖, 64 checkpoints와 FIFO sentinel, 공통 empty 보정; 작은 이득은 9회차 pooled 짝 차이 99% bootstrap과 같은 세션 A/A 대조. AA 중앙값의 절댓값을 사용한 보수적인 이득 기준.',rows:bounds.rows,ranking,fixSpecs:specs,contracts,thresholdCoverage,limitations:['제거/재생 변형은 고정 픽스처의 작업 비용을 귀속하는 관측 상한이며 수학적인 무오버헤드 상한이 아닙니다. guard/replay 및 JIT 차이가 남습니다.','A1/O1의 tape는 측정에서만 폼 밖 참조를 재생합니다. 수정안은 폼 간 공유를 하지 않습니다. 값 digest의 일치는 일반 참조·오류·구독자 계약의 검증이 아닙니다.','E1/D1은 필수 revision/payload/global-state 일을 제거합니다. 이 전체를 제품에서 생략하는 변경은 제안하지 않습니다.','105C-01의 회귀 행은 해당 제거 변형의 결과입니다. 실제 수정안의 채택에는 계약 확인 뒤 그 변경 하나의 새로운 판정이 필요합니다.','CPU의 inline 비용은 caller self에 잡힐 수 있고 짧은 샘플 구간은 인접 드라이버 프레임과 섞일 수 있습니다. GC/program/idle은 분모에 그대로 두고 verdict 시간으로 환산하지 않습니다.']},audit};
if(process.argv[2]==='--summary')console.log(JSON.stringify({...packet,cpu:cpu.map(({functions,...row})=>row),audit:{...audit,artifactManifest:undefined,artifactManifestFile:'profile-109-update/audit-manifest.json'}}));
else if(process.argv[2]==='--manifest')console.log(JSON.stringify({HEAD,artifactManifest,maximumArtifactBytes:audit.maximumArtifactBytes}));
else if(process.argv[2]==='--markdown'){
  const out=['# 109 갱신 경로 귀속·제거 실험 상한','',`HEAD: \`${HEAD}\`. 측정만 수행했습니다. 제품 src·Git·설치·원장은 변경하지 않았습니다.`,'','## 판정 요약','',`flat-100 첫 갱신의 신규 (가) 실패는 **보정 종단의 microtask 이후 sentinel tail과 주변 중앙값의 비가산 합성**에 귀속됩니다. 107→108에서 tail 중앙값은 17.583 µs로 같고, 빈 대기 보정은 14.291→14.292 µs입니다. 비가산 항만 0.375→6.626 µs로 커져 차이가 3.667→9.917 µs로 증가했습니다. 쓰기·정착·배달 실행 몫이 어느 한 끝점에서 빠진 현상은 아닙니다.`,`새 세 회차의 (가)는 **통과**, 차이/잡음 **8.583/10.707 µs**, 새/0.16.0 **1.795699×**, 공식 수치 판정은 **미달**입니다. 새로운 소유자 수용 처분은 만들지 않았습니다.`,`array-100 BF/첫 갱신의 공유 원인: **예**. 같은 종단 보정/중앙값 합성 문제입니다. 다만 107은 비가산 항 7.959 µs, 108은 tail 잔차 25.792 µs가 주항입니다. interactionCount=1이라 BF와 첫 갱신은 같은 101개 표본을 사용합니다. 이번에도 (가) 미통과(17.833/12.000 µs)여서 공식 판정은 보류합니다.`,'','## 설계와 시계','',packet.bounds.method,'','Part 1은 기존 95C-01 development 도구의 HEAD·warmup 20·data-module 경로만 메모리에서 바꿨습니다. 세 회차 순서는 old→new / new→old / old→new이며 각 101표본입니다. 구 엔진의 (나) 합은 원 규칙에 따라 선택했고 새 엔진에는 적용하지 않았습니다. 양 끝점을 같은 호출에서 기록하며 표본 제거·음수 clipping·재측정 행 선택을 하지 않았습니다. Part 2는 production 판정 열입니다. 두 열의 절대 시간을 직접 합치거나 뺄 수 없습니다.','',`원문: 106C-01은 origin/1.0.0-beta의 round-106-closing.md(416613c70)에서 읽었고, 105C-01·최소 크기 부록·95C-01·104 소유자 답도 같은 로컬 ref에서 읽었습니다. 설치나 외부 fetch는 수행하지 않았습니다.`,'','## Part 1 — 불일치의 위치와 원인','',`원 도구의 measure는 operation → 64 Promise checkpoints → micro clock → FIFO setImmediate sentinel clock 순서입니다. 실제 동기 쓰기와 정착·배달은 두 끝점이 공유합니다. 새 엔진의 모든 scheduler 진단에서 scheduled=0, pending=0, 추가 128 checkpoints/다음 sentinel의 예약·실행=0입니다. 이 worker에는 React render/commit이 없습니다.`,`검증 차이는 med(end)-med(micro)-(C-M)입니다. 이것을 [med(end-micro)-(C-M)] + [med(end)-med(micro)-med(end-micro)]로 정확히 분해했습니다. 첫 항은 tail 대기의 잔차, 둘째는 주변 중앙값의 비가산 항입니다. 다음 표는 모든 원시 표본을 그대로 사용합니다.`,'','| 회차 / fixture | micro 중앙값 µs | end 중앙값 µs | tail 중앙값 µs | C−M µs | tail 잔차 µs | 비가산 항 µs | (가) 차이 µs |','| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |'];
  for(const r of decomposition)out.push(`| ${r.round} / ${r.fixture} | ${us(r.microMs)} | ${us(r.endMs)} | ${us(r.tailMedianMs)} | ${us(r.waitMs)} | ${us(r.tailResidualMs)} | ${us(r.nonAdditiveMs)} | ${us(r.differenceMs)} |`);
  out.push('','107→108 flat-100의 raw micro 중앙값은 62.583→56.416 µs로 줄었으나 raw end는 80.541→80.625 µs입니다. tail 중앙값은 같아도 두 주변 중앙값이 선택하는 표본 순위가 달라져 이 차이를 만들었습니다. FIFO sentinel은 완료 순서를 보장하며 동일한 대기 길이는 보장하지 않습니다. 빈 호출 하나의 C/M 상수를 모든 상태에 적용한 잔차와 이 비가산성이 (가)에 남습니다. 그 공식 정의를 고쳐 이번 행을 통과시키지는 않았습니다.','',`동일 HEAD의 별도 진단에서 첫 갱신 tail self는 flat-100 idle 69.52%, array-100 idle 72.46%였고 program/Node check 큐·드라이버가 뒤를 이었습니다. array의 post-mount/capture 위치에 실제 쓰기 대신 먼저 잰 빈 shadow의 tail 중앙값은 29.542 µs, 일반 빈 호출은 17.792 µs였습니다. 엔진 쓰기가 없는 호출에서도 같은 위치의 대기가 달라집니다. shadow 뒤 첫 쓰기의 tail은 18.459 µs였습니다. 이는 제품의 새로운 비동기 실행이 아니라 호출 위치에 따른 대기 보정 불일치를 뒷받침합니다. 이 계측/프로파일 진단은 공식 표본에 섞지 않았습니다. OS의 개별 wake-up 원인을 특정했다는 주장은 하지 않습니다.`,'','### 공식 재측정 — 모든 행과 회차','',`공통 보정: C=${us(official.calibration.C)} µs, M=${us(official.calibration.M)} µs, wait=${us(official.calibration.wait)} µs, empty=${official.calibration.emptyCalls}호출. empty residual p95=${us(official.calibration.emptyNoise)} µs.`,'','| fixture / 작업 | 새/구 median ms | 배율 | 회차 1 / 2 / 3 배율 | (가) 차이/잡음 µs | pooled / 모든 회차 | 구 열 | 공식 판정 |','| --- | --- | ---: | --- | --- | --- | --- | --- |');
  for(const r of official.rows)out.push(`| ${r.fixture} / ${r.mode} | ${r.new.metric.median.toFixed(6)} / ${r.old.metric.median.toFixed(6)} | ${r.ratio.toFixed(6)} | ${r.runRatios.map(x=>x.toFixed(6)).join(' / ')} | ${us(r.new.validation.differenceMs)} / ${us(r.new.validation.noiseMs)} | ${r.new.validation.withinNoise?'통과':'미통과'} / ${r.new.validation.allRunsWithinNoise?'통과':'미통과'} | ${r.old.column} | ${r.verdict} |`);
  out.push('','| flat-100 첫 갱신 회차 | (가) 차이 µs | 잡음 µs | 판정 |','| --- | ---: | ---: | --- |');for(const r of official.rows.find(r=>r.fixture==='flat-100'&&r.mode==='update-first').new.runs)out.push(`| ${r.run} | ${us(r.differenceMs)} | ${us(r.noiseMs)} | ${r.withinNoise?'통과':'미통과'} |`);
  out.push('','## Part 2 — 계측 없는 steady CPU top 20','',`각 fresh process에서 20회 예열 뒤 mount/BF 준비를 profiler 시작 전에 끝내고, 첫/이후 쓰기 101개를 연속 수행했습니다. 첫은 fresh root의 첫 쓰기, 이후는 fixture BF를 완료한 retained root의 다음 쓰기입니다. 101개의 준비된 root를 순차 소비하며 수집 중 schema clone/mount/강제 GC를 하지 않습니다. 요청 interval은 10 µs입니다. 세 fresh process의 시간 가중치를 pooled했고 재귀 total은 같은 함수당 한 번만 셉니다.`,`실행 구간의 모든 샘플 가중치를 분모로 유지합니다. GC/program/idle/드라이버를 빼거나 함수들만으로 정규화하지 않았습니다. 같은 수집의 64 checkpoints+sentinel 전체 구간 결과는 raw JSON의 endpointCpu에 있습니다. 앞선 full-endpoint 탐색 CPU 자료도 삭제하지 않았습니다. 짧은 구간의 샘플링 경계 오차와 inline 비용 때문에 caller self가 해당 함수의 독립 제거 가능 비율인 것은 아닙니다.`);
  for(const c of cpu){out.push('',`### ${c.fixture} / ${c.mode==='first'?'첫 갱신':'이후 갱신'}`,'',`3×101 updates, 유효 sample intervals=${c.sampleIntervals}, 분모=${c.denominatorUs.toFixed(0)} µs, 시계 window=${c.windowUs.toFixed(0)} µs, self 보존=${(c.selfConservationUs/c.denominatorUs*100).toFixed(3)}%.`,'','| 함수 / 원본 위치 | self % | total % | self µs/update | total µs/update |','| --- | ---: | ---: | ---: | ---: |');for(const f of c.top20)out.push(`| \`${f.function}\` · \`${f.file.replace('packages/canard/schema-form/src/','src/')}:${f.line}\` | ${pct(f.selfPct)} | ${pct(f.totalPct)} | ${(f.selfUs/303).toFixed(3)} | ${(f.totalUs/303).toFixed(3)} |`);}
  out.push('','## 잡음 밖 상한의 순위와 변경 하나의 수정안','',`같은 후보의 fixture 이득을 합하지 않습니다. D1⊃E1, O1⊃A1이며 C1/F1/P1에도 일부 겹침이 있습니다. 순위는 각 후보의 잡음 밖 행 중 최대 짝 차이를 보여주는 인덱스입니다. 전체 행과 회귀는 다음 표가 기준입니다. 제거된 필수 일 전체가 실제 수정안의 기대 이득은 아닙니다.`,'','| 순위 / ID | 제거 범위 | 최대 행 | 이득 µs [99% 구간] | 회차 | 잡음 밖 행 / 변형 회귀 행 | 계약 질문 |','| --- | --- | --- | --- | ---: | --- | --- |');ranking.forEach((s,i)=>{const r=s.best;out.push(`| ${i+1} / ${s.id} | ${s.label} | ${r?`${r.fixture} / ${r.mode}`:'미입증'} | ${r?`${us(r.pairedMedianMs)} [${us(r.ci99.low)}, ${us(r.ci99.high)}]`:'—'} | ${r?.runs??'—'} | ${s.positiveRows} / ${s.materialRegressions.length} | ${s.contracts.join(', ')||'E/V 직접 수정 없음'} |`);});
  for(const s of ranking)out.push('',`### ${s.id} — ${s.label}`,'',`소유자: \`src/${s.owner}\`; 변경 위치: \`${s.file}\`. 수정안 하나: ${s.fix}`,`제거 실험: ${s.elision}`,`계약 표기: ${s.contracts.length?`**${s.contracts.join(', ')}에 닿음 — 코드 전 원장 질문**`:'EVENT-007 / VALUE-012 직접 수정 없음'}. ${s.why}`);
  out.push('','### 첫 갱신의 크기 독립 고정 몫','',`F1은 leaf의 진입과 빈 단계 검사를 다루며 필드 전체를 순회하는 작업을 제거하지 않습니다. C1은 이 정상 값 픽스처의 빈 진단/메모 정리 몫입니다. flat-100→flat-500은 전체 필드가 5배지만 한 쓰기의 바뀐 경로는 leaf와 root 두 곳입니다. 따라서 이 두 범위의 이득을 고정 몫의 측정 가능한 부분 상한으로 따로 보며, 중첩 폼의 깊이·조상 수 효과까지 크기 독립이라고 부르지는 않습니다. 모든 쓰기당 고정 비용을 0으로 만든다는 설계 변경은 측정하거나 제안하지 않았습니다.`,'','| 범위 / fixture | 첫 이득 µs [99% 구간] | 회차 | 판정 |','| --- | --- | ---: | --- |');for(const variant of ['fixed-shell','commit-bookkeeping','fixed-empty-latent'])for(const fixture of fixtures){const r=bounds.rows.find(r=>r.variant===variant&&r.fixture===fixture&&r.mode==='first');out.push(`| ${variant} / ${fixture} | ${us(r.pairedMedianMs)} [${us(r.ci99.low)}, ${us(r.ci99.high)}] | ${r.runs} | ${r.verdict} |`);}
  out.push('','## 모든 제거 실험의 판정 열','',`이득은 HEAD−variant의 ordinal 짝 차이 중앙값입니다. 3회차는 각 회차 이득이 해당 회차 잡음보다 커야 합니다. 작은 이득의 행이 있는 후보/fixture는 worker가 두 update 모드를 함께 내므로 둘 다 9회차 자료를 유지했습니다. 9회차는 pooled 99% 구간 하한>0 및 이득>같은 행 A/A 중앙값 절댓값을 요구했습니다. 회귀는 구간 상한<0이고 |중앙값|>max(|A/A|, HEAD median×0.005)입니다. 원 결정의 signed A/A 비교보다 보수적으로 절댓값을 사용했습니다.`,`A1/O1/F1/P1/Q1/W1의 일부 later 제거 변형은 회귀 조건을 채웁니다. 이것을 숨기거나 해당 표본을 버리지 않았습니다. 이 실험 변형을 제품 수정으로 채택하지 않으며 실제 수정은 계약 확인 뒤 별도 재측정해야 합니다.`,'','| fixture / 모드 / ID | 회차 | HEAD/variant median µs | 짝 이득 µs [99%] | 최대 회차 잡음 µs | A/A µs | 회귀 바닥 µs | 판정 |','| --- | ---: | --- | --- | ---: | ---: | ---: | --- |');for(const fixture of fixtures)for(const mode of ['first','later'])for(const s of specs){const r=bounds.rows.find(r=>r.fixture===fixture&&r.mode===mode&&r.variant===s.variant);out.push(`| ${fixture} / ${mode} / ${s.id} | ${r.runs} | ${us(r.headMedianMs)} / ${us(r.variantMedianMs)} | ${us(r.pairedMedianMs)} [${us(r.ci99.low)}, ${us(r.ci99.high)}] | ${us(Math.max(...r.perRun.map(x=>x.noiseMs)))} | ${us(r.aaMedianMs)} | ${us(r.regressionFloorMs)} | ${r.verdict}${r.materialRegression?' — 제거 변형 채택 불가':''} |`);}
  out.push('','### A/A 대조 — HEAD 대 HEAD 9회차','', '| fixture / 모드 | 짝 중앙값 µs [99%] | HEAD median µs |','| --- | --- | ---: |');for(const r of bounds.rows.filter(r=>r.variant==='control'))out.push(`| ${r.fixture} / ${r.mode} | ${us(r.pairedMedianMs)} [${us(r.ci99.low)}, ${us(r.ci99.high)}] | ${us(r.headMedianMs)} |`);
  out.push('','## EVENT-007 / VALUE-012 — 코드 전 원장 질문','');for(const [id,c]of Object.entries(contracts)){out.push(`### ${id}`,'',`정확한 문장 (${c.source}):`,'',`> ${c.sentence}`,'',`보충: ${c.supplement}`,'');for(const s of specs.filter(s=>s.contracts.includes(id)))out.push(`- **${s.id}**: ${s.why}`);out.push('');}
  out.push('D1/E1은 EVENT-007, A1/O1은 VALUE-012 질문입니다. 다른 수정안은 E/V 구현을 직접 고치지 않는다고 명시했으며, 그 경계를 넘는 실제 수정이면 다시 원장 질문으로 올려야 합니다. 정착 설계 변경·구독자 유무에 따른 revision 생략·새 공개 계약·폼 간 공유는 어느 수정안에도 없습니다.','', '## ≥5% self+children 귀속의 빠짐 확인','',`self+children은 inclusive total입니다. self와 total을 더하지 않습니다. 모든 pooled ≥5% 프레임을 아래에 기록했습니다. 위임 부모는 자손 상한을 다시 독립 이득으로 더하지 않았습니다. VM/드라이버는 분모에 남긴 범위이며 독립 제품 owner의 개선안으로 만들지 않았습니다.`,'','| fixture / 모드 | 함수 | self / total % | 상한 ID / 귀속 |','| --- | --- | --- | --- |');for(const r of thresholdCoverage)out.push(`| ${r.fixture} / ${r.mode} | \`${r.function}\` · \`${r.file.replace('packages/canard/schema-form/src/','src/')}\` | ${pct(r.selfPct)} / ${pct(r.totalPct)} | ${r.ids.join(', ')||r.disposition} |`);
  out.push('','## 실행 감사·한계·재현','',`유효 worker ${audit.successfulWorkers}개: 공식 ${audit.officialWorkers}, 제거 실험/A/A ${audit.boundWorkers}, CPU ${audit.cpuWorkers}(최종 실행 창 24개와 초기 전체 끝점 탐색 18개), 끝점 진단 ${audit.diagnosticWorkers}. 모두 code=0, signal=null, natural=true입니다. 측정 timeline 겹침은 0이며 각 subprocess는 정상 종료했습니다. esbuild는 두 bundle을 메모리에서 만든 뒤 stdin EOF로 종료했고 timing 시작 전에 끝났습니다. 최대 worker 내부 경과 ${audit.maxWorkerElapsedMs} ms; 확장 묶음은 ${audit.extensionBatchElapsedMs.map(x=>(x/1000).toFixed(3)).join(' / ')}초입니다. 8분을 넘는 실행 명령, 강제 kill, background 측정은 없습니다.`,`산출물은 profile-109-update/의 JSON·mjs와 요청한 보고서/summary뿐입니다. 현재 원시/도구 파일 최대 ${audit.maximumArtifactBytes} bytes로 각 5 MB 이하입니다. write:false bundle/map은 메모리에서만 사용했고 TMPDIR/sourceURL/outfile 위치는 지정된 저장소 밖 bundles입니다. Node compile cache는 비활성화했습니다. tracked diff는 없으며 HEAD를 끝에 다시 확인했습니다. Git 쓰기·설치·제품 test/build는 실행하지 않았습니다.`,'',...audit.preflightIssues.map(x=>'- 준비 단계 기록: '+x),'',...packet.bounds.limitations.map(x=>'- '+x),'','재현 CLI(한 worker씩, 순차 실행):','', '```sh',"TMPDIR='/private/tmp/claude-501/-Users-Vincent-Workspace-albatrion/c8aaf054-1ea7-43d3-b3c1-a4196f8407e1/scratchpad/bundles' NODE_DISABLE_COMPILE_CACHE=1 GIT_OPTIONAL_LOCKS=0 yarn exec /opt/homebrew/Cellar/node/26.10.0_2/bin/node --expose-gc packages/canard/schema-form/architecture/verification/07-switch/profile-109-update/measure.mjs --official flat-100 off 1 old",'```','', '동일 prefix로 --cpu <fixture> <first|later> <1|2|3>, --bound <fixture> <variant> <run>, --diagnose <fixture> <run> <original|shadow-unprofiled>를 실행합니다. official은 원 세 회차 순서를 유지하고 bound는 raw 파일의 3/9 회차 수를 유지합니다. stats.mjs --official/--historical/--bounds와 report.mjs --summary/--markdown은 stdout artifact renderer입니다. stdout은 native 파일 도구로 보존합니다. 원문·해시·시계 창·303/909쌍·진단·회차별 잡음은 [원시 자료](profile-109-update/)와 [구조화 요약](profile-109-update-summary.json)에 있습니다.','');
  console.log(out.join('\n'));
}else throw new Error('Use --summary or --markdown');
