// Measurement reporter; outputs JSON for native artifact writes.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const work=path.dirname(fileURLToPath(import.meta.url)), D=path.dirname(work);
const read=(file,folder=work)=>JSON.parse(fs.readFileSync(path.join(folder,file+'.json'),'utf8'));
const q=(values,p)=>values.toSorted((a,b)=>a-b)[Math.ceil(values.length*p)-1];
const median=values=>q(values,.5);
const metric=values=>({median:median(values),p99:q(values,.99),samples:values.length});
function bootstrap(values,seed=9501){let state=seed>>>0;const estimates=[];for(let trial=0;trial<1000;trial++){const sample=[];for(let i=0;i<values.length;i++){state=(Math.imul(state,1664525)+1013904223)>>>0;sample.push(values[Math.floor(state/4294967296*values.length)]);}estimates.push(median(sample));}const center=median(values),low=q(estimates,.005),high=q(estimates,.995);return {low,high,halfWidth:Math.max(center-low,high-center),resamples:1000,seed};}
function calibrate(records){const empty=records.flatMap(r=>[...r.timings['empty-before'],...r.timings['empty-after']]),waiting=empty.map(x=>x[1]-x[0]),waitMedian=median(waiting);const C=median(empty.map(x=>x[1])),M=median(empty.map(x=>x[0]));return {C,M,wait:C-M,emptyNoise:q(waiting.map(x=>Math.abs(x-waitMedian)),.95),emptyEndCi:bootstrap(empty.map(x=>x[1]),9501),emptyMicroCi:bootstrap(empty.map(x=>x[0]),9502),emptyCalls:empty.length};}
function evaluate(records,mode,calibration){const {C,M,emptyNoise,emptyEndCi,emptyMicroCi}=calibration,callCount=mode==='update'?records[0].summary.interactionCount:1,versions={};for(const version of ['new','old']){const runs=[1,2,3].map(run=>{const t=records.find(r=>r.summary.run===run&&r.summary.version===version).timings;const sentinel=t[mode].map(x=>x[1]-C*callCount),microtask=t[mode].map(x=>x[0]-M*callCount),callback=t[mode+'-callback'],sum=microtask.map((x,i)=>x+callback[i]),expected=version==='new'?microtask:sum;const noise=Math.max(.001,callCount*emptyNoise+bootstrap(sentinel,run*100+95).halfWidth+bootstrap(expected,run*100+96).halfWidth+callCount*(emptyEndCi.halfWidth+emptyMicroCi.halfWidth));const difference=median(sentinel)-median(expected);return {run,sentinel,microtask,callback,sum,differenceMs:difference,noiseMs:noise,withinNoise:Math.abs(difference)<=noise};});const pooled=Object.fromEntries(['sentinel','microtask','callback','sum'].map(key=>[key,runs.flatMap(r=>r[key])]));const expected=version==='new'?pooled.microtask:pooled.sum,noise=Math.max(.001,callCount*emptyNoise+bootstrap(pooled.sentinel,9593).halfWidth+bootstrap(expected,9594).halfWidth+callCount*(emptyEndCi.halfWidth+emptyMicroCi.halfWidth));const difference=median(pooled.sentinel)-median(expected),withinNoise=Math.abs(difference)<=noise,fallback=version==='old'&&(!withinNoise||runs.some(r=>!r.withinNoise));versions[version]={fallback,column:fallback?'(나) microtask + callback 합':'종단',metric:metric(fallback?pooled.sum:pooled.sentinel),sentinel:metric(pooled.sentinel),microtask:metric(pooled.microtask),validation:{differenceMs:difference,noiseMs:noise,withinNoise,allRunsWithinNoise:runs.every(r=>r.withinNoise)},runs:runs.map(r=>({run:r.run,differenceMs:r.differenceMs,noiseMs:r.noiseMs,withinNoise:r.withinNoise,metric:metric(fallback?r.sum:r.sentinel)}))};}const ratio=versions.new.metric.median/versions.old.metric.median,runRatios=[0,1,2].map(i=>versions.new.runs[i].metric.median/versions.old.runs[i].metric.median),tie=runRatios.some(x=>x<=1.5)&&runRatios.some(x=>x>1.5),valid=versions.new.validation.withinNoise&&versions.new.validation.allRunsWithinNoise;return {mode,callCount,ratio,runRatios,tie,target:1.5,met:tie||ratio<=1.5,verdict:valid?(tie?'충족(동률)':ratio<=1.5?'충족':'미달'):'보류((가) 미통과)',...versions};}
function official(){const records=['flat-100','array-100'].flatMap(f=>[1,2,3].flatMap(run=>['old','new'].map(v=>read(`official-${f}-off-r${run}-${v}`)))),calibration=calibrate(records);return {calibration,rows:['flat-100','array-100'].flatMap(f=>['update','update-first','update-later'].map(mode=>({fixture:f,...evaluate(records.filter(r=>r.summary.fixture===f),mode,calibration)})))};}
function historical(){const result=[];for(const round of [107,108])for(const fixture of ['flat-100','array-100']){const folder=path.join(D,round===107?'profile-107-remaining':'profile-108-ratios'),calibration=round===107?read('profile-107-remaining-summary',D).calibration:read('calibration',folder).byValidation.off;const records=[1,2,3].flatMap(run=>['old','new'].map(v=>read(round===107?`official-${fixture}-r${run}-${v}`:`official-${fixture}-off-r${run}-${v}`,folder)));for(const mode of ['update','update-first','update-later']){const row=evaluate(records,mode,calibration);const endpoint=records.filter(r=>r.summary.version==='new').map(r=>({run:r.summary.run,emptyTail:metric([...r.timings['empty-before'],...r.timings['empty-after']].map(x=>x[1]-x[0])),operationTail:metric(r.timings[mode].map(x=>(x[1]-x[0])/row.callCount)),ordering:r.summary.ordering[mode]}));result.push({round,fixture,...row,endpoint});}}return result;}
const command=process.argv[2];
if(command==='--official')console.log(JSON.stringify(official()));
else if(command==='--historical')console.log(JSON.stringify(historical()));
else if(command==='--bounds') {
  const files=fs.readdirSync(work).filter(f=>/^bound-.*\.json$/.test(f)),groups=new Map();
  for(const file of files){const o=read(file.slice(0,-5));for(const mode of ['first','later']){const key=o.fixture+'|'+o.variant+'|'+mode,rows=groups.get(key)??[];rows.push({run:o.run,head:o.timings.head[mode],variant:o.timings.variant[mode],empty:o.empty});groups.set(key,rows);}}
  const rows=[];for(const [key,runs]of groups){const [fixture,variant,mode]=key.split('|'),deltas=runs.flatMap(r=>r.head.map((x,i)=>x-r.variant[i])),ci=bootstrap(deltas,10501),center=median(deltas),headMedian=median(runs.flatMap(r=>r.head)),variantMedian=median(runs.flatMap(r=>r.variant));const perRun=runs.map(r=>{const h=bootstrap(r.head,r.run*100+1),v=bootstrap(r.variant,r.run*100+2),e=r.empty,noise=Math.max(.001,h.halfWidth+v.halfWidth,q(e.map(x=>Math.abs(x-median(e))),.95));return {run:r.run,headMs:median(r.head),variantMs:median(r.variant),deltaMs:median(r.head.map((x,i)=>x-r.variant[i])),noiseMs:noise};});rows.push({fixture,variant,mode,runs:runs.length,samples:deltas.length,headMedianMs:headMedian,variantMedianMs:variantMedian,pairedMedianMs:center,ci99:ci,perRun,threeRunAboveNoise:runs.length>=3&&perRun.every(r=>r.deltaMs>r.noiseMs),percent:center/headMedian*100});}
  for(const row of rows){const control=rows.find(r=>r.fixture===row.fixture&&r.mode===row.mode&&r.variant==='control');row.aaMedianMs=control?.pairedMedianMs;row.regressionFloorMs=Math.max(Math.abs(control?.pairedMedianMs??0),row.headMedianMs*.005);row.aboveNoise=row.threeRunAboveNoise||(row.runs===9&&row.ci99.low>0&&row.pairedMedianMs>Math.abs(control?.pairedMedianMs??Infinity));row.materialRegression=row.ci99.high<0&&Math.abs(row.pairedMedianMs)>row.regressionFloorMs;row.verdict=row.aboveNoise?'잡음 밖 상한':row.materialRegression?'측정 변형 회귀':'미입증';}
  console.log(JSON.stringify({rows}));
} else throw new Error('Use --official, --historical or --bounds');
