export const icons = {
  bulletDone: '●',
  bulletActive: '◐',
  bulletPending: '○',
  triangleRight: '▸',
  check: '✓',
  cross: '✗',
  warning: '⚠',
  question: '?',
  plus: '+',
  equals: '=',
  minus: '−',
  tilde: '~',
  blockFull: '█',
  blockEmpty: '░',
  dash: '─',
  divider: '───',
  boxTopLeft: '╭',
  boxTopRight: '╮',
  boxBottomLeft: '╰',
  boxBottomRight: '╯',
  boxHorizontal: '─',
  boxVertical: '│',
  boxDoubleTopLeft: '┌',
  boxDoubleTopRight: '┐',
  boxDoubleBottomLeft: '└',
  boxDoubleBottomRight: '┘',
} as const;

export type IconName = keyof typeof icons;
