export const SCHEMA_FORM_WARNING = 'SCHEMA_FORM_WARNING';

export const ALL_OF_KEYWORD_IGNORED_FOR_FORM =
  'ALL_OF_KEYWORD_IGNORED_FOR_FORM';
export const NESTED_COMPOSITION_IGNORED_FOR_FORM =
  'NESTED_COMPOSITION_IGNORED_FOR_FORM';
